port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  use-host: true
  enhanced-mode: fake-ip
  listen: 127.0.0.1:7874
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fallback:
    - 1.0.0.1
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.mcdn.bilivideo.cn"
    - +.media.dssott.com
proxies:
  - name: (ID) Amazon.com, Inc 🇮🇩
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 14814b9d-11df-411c-b023-99198d0d4cc1
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /id-amz
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true
  - name: (ID) RumahWeb 🇮🇩
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: f60e55d2-57e0-40e8-8146-56eeff893719
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /id-rweb
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true
  - name: (ID) PT. Telekomunikasi 🇮🇩
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 0959758e-3068-475b-bbef-d3956439f7b9
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /id-tele
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true
  - name: (ID) Pt Pusat Media 🇮🇩
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 540b3e3d-1cd5-4f05-bc51-2393248b9351
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /id-pusat
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true
  - name: (SG) DigitalOcean, LLC 🇸🇬
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 663c3b5d-02f6-487a-bb98-c12ae0b1f144
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /sg-do
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true
  - name: (SG) Contabo Asia 🇸🇬
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 44639afd-22b9-40c0-af8b-681a744e494f
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /sg-cntb
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true
  - name: (SG) Oracle Corporation 🇸🇬
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 0a00bf52-ca9f-48c8-a874-ac7f0a69c2fc
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /sg-orcl
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true
  - name: (SG) Regxa Company 🇸🇬
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 81f8c61b-74f2-446a-926f-adf1cc2f47b4
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /sg-rgxa
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true

proxy-groups:
  - name: INTERNET UMUM 🌍
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - (ID) Amazon.com, Inc 🇮🇩
      - (ID) RumahWeb 🇮🇩
      - (ID) PT. Telekomunikasi 🇮🇩
      - (ID) Pt Pusat Media 🇮🇩
      - (SG) DigitalOcean, LLC 🇸🇬
      - (SG) Contabo Asia 🇸🇬
      - (SG) Oracle Corporation 🇸🇬
      - (SG) Regxa Company 🇸🇬
      
proxy-groups:
  - name: AKUN ID 🇮🇩
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - (ID) Amazon.com, Inc 🇮🇩
      - (ID) RumahWeb 🇮🇩
      - (ID) PT. Telekomunikasi 🇮🇩
      - (ID) Pt Pusat Media 🇮🇩
  
  - name: AKUN SG 🇸🇬
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - (SG) DigitalOcean, LLC 🇸🇬
      - (SG) Contabo Asia 🇸🇬
      - (SG) Oracle Corporation 🇸🇬
      - (SG) Regxa Company 🇸🇬
      
  - name: IKLAN ⛔
    type: select
    proxies:
     - AKUN SG 🇸🇬
     - REJECT

  - name: GAME 🎲
    type: select
    proxies:
     - AKUN ID 🇮🇩
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN ⛔
 - RULE-SET,Game,GAME 🎲
 - RULE-SET,Sosmed,AKUN ID 🇮🇩
 - RULE-SET,indo,AKUN ID 🇮🇩
 - RULE-SET,Umum,AKUN SG 🇸🇬
 - RULE-SET,Streaming,AKUN SG 🇸🇬
 - RULE-SET,Bankid,AKUN ID 🇮🇩
 - RULE-SET,Tiktok,AKUN SG 🇸🇬
 - RULE-SET,Meta,AKUN ID 🇮🇩
 - RULE-SET,PortGame,GAME 🎲
 - MATCH,INTERNET UMUM 🌍


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  
