port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  use-host: true
  enhanced-mode: fake-ip
  listen: 127.0.0.1:7874
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fallback:
    - 1.0.0.1
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.mcdn.bilivideo.cn"
    - +.media.dssott.com

proxies:
  - name: (ID) Linode 🇮🇩
    server: min.biz.id
    port: 443
    type: trojan
    password: ed01654f-8cea-42d1-8ea0-7646f994f3d6
    skip-cert-verify: true
    sni: graph.instagram.com.min.biz.id
    network: ws
    ws-opts:
      path: /172.232.239.151-587
      headers:
        Host: min.biz.id
    udp: true

  - name: (SG) Tencent 🇸🇬
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 78bd974c-31af-45ed-b9e0-f2d8b5ffd680
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.vip-12.indoxray.top
    network: ws
    ws-opts:
      path: /websocket-vless
      headers:
        Host: ava.game.naver.com.vip-12.indoxray.top
    udp: true

proxy-groups:
  - name: PR0XIES
    type: load-balance
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    interval: 180
    udp: true
    proxies:
      - (SG) Tencent 🇸🇬
      - (ID) Linode 🇮🇩

rules:
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - RULE-SET,Block,PR0XIES
  - RULE-SET,Game,PR0XIES
  - RULE-SET,Sosmed,PR0XIES
  - RULE-SET,Indo,PR0XIES
  - RULE-SET,Umum,PR0XIES
  - RULE-SET,Streaming,PR0XIES
  - RULE-SET,Banking,PR0XIES
  - RULE-SET,Meta,PR0XIES
  - RULE-SET,PortGame,PR0XIES
  - MATCH,PR0XIES

rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml
  Indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Banking:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml
